
---
  - name: install python, pip etc
    shell: apt-get -y install "{{ item }}"
    with_items:
        - pip 
        - python3-mysqldb
        - default-libmysqlclient-dev 
        - build-essential
    state: present

  - name: Install MySQL server
    shell: apt-get -y install mysql-server

  - name: Install MySQL client
    shell: apt-get -y install mysql-client

  - name: update mysql root password for all root accounts
    mysql_user:
    name: root
    host: localhost
    password: "{{ sql_root_password }}"

  - name: Create a new database with name
    community.mysql.mysql_db:
    name: "{{sql_extra_database}}"   
    state: present

 - name: Create database user with name 'Tom' and password 'the_password' with all database privileges
   community.mysql.mysql_user:
    name: "{{sql_extra_user}}"
    password: "{{sql_extra_user_password}}"
    priv: 
       "{{sql_extra_database}}": '*.*:ALL'
    state: present

